version: '2.1'

services:
  app:
    restart: always
    build: ./
    volumes:
    - ioi_static:/usr/src/app/static/
    - ioi_media:/usr/src/app/media/
    depends_on:
    - postgres
    - redis
    ports:
    - 9000:9000
    environment:
      SECRET_KEY: 'secret_key_for_development_3969b4b149439648a52aa663bd740a4f'
      SESSION_COOKIE_SECURE: 0
      DB_HOST: postgres
      DB_USER: &db_user postgres
      DB_PASSWORD: &db_password postgres
      DB_NAME: &db_name ioitrans
      REDIS_HOST: redis
      REDIS_DB: 1
      GUNICORN_WORKERS: 2
      PRINT_SYSTEM_URL: http://192.168.10.21:5000
      MONITOR_URL: http://127.0.0.1:9000 #JAVA app for monitoring user status on the big screen
      DRAFT_PRINTER: draft_printer  # Printer or class name used for DRAFT Translations Printing
      FINAL_PRINTER: final_printer  # Printer or class name used for FINAL Translations Printing

  postgres:
    restart: always
    image: postgres:9.6-alpine
    volumes:
    - ioi_pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ioitrans

  redis:
    restart: always
    image: redis:3.2-alpine

volumes:
  ioi_pgdata:
  ioi_static:
  ioi_media:
