version: '3.1'

services:
  web:
    restart: always
    build: ./
    volumes:
    - ioi_source:/usr/src/app/
    depends_on:
    - postgres
    - redis
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ioitrans
      EMAIL_HOST_USER: test
      EMAIL_HOST_PASSWORD: test
      DJANGO_SETTINGS_MODULE: Translation.production_settings
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
    - 8000:80
    links:
    - web:web
    volumes:
    - ioi_source:/usr/src/app
  
  postgres:
    restart: always
    image: postgres:9.6-alpine
    volumes:
    - ioi_pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ioitrans
  
  redis:
    restart: always
    image: redis:3.2-alpine

volumes:
  ioi_pgdata:
  ioi_source:
