version: '3.1'

services:
  web:
    restart: always
    build: ./
    command: gunicorn
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_USER: &db_user postgres
      DB_PASSWORD: &db_password postgres
      DB_NAME: &db_name ioitrans
      GUNICORN_WORKERS: 2

  nginx:
    restart: always
    build: ./
    command: nginx
    environment:
      NO_DATABASE: 1
    ports:
      - 8000:80

  postgres:
    restart: always
    image: postgres:9.6-alpine
    volumes:
      - ioi_pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: *db_user
      POSTGRES_PASSWORD: *db_password
      POSTGRES_DB: *db_name

  redis:
    restart: always
    image: redis:3.2-alpine

volumes:
  ioi_pgdata:
