version: '3.1'

services:
  web:
    restart: always
    build: ./
    volumes:
    - ioi_static:/usr/src/app/static/
    - ioi_media:/usr/src/app/media/
    depends_on:
    - postgres
    - redis
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ioitrans
      EMAIL_HOST_USER: test
      EMAIL_HOST_PASSWORD: test
      DJANGO_SETTINGS_MODULE: Translation.production_settings
      GUNICORN_WORKERS: 40
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
    - 8000:80
    links:
    - web:web
    volumes:
    - ioi_static:/usr/src/app/static/:ro
    - ioi_media:/usr/src/app/media/:ro
  
  postgres:
    restart: always
    image: hub.docker.hamravesh.ir/library/postgres:9.6-alpine
    volumes:
    - ioi_pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ioitrans
  
  redis:
    restart: always
    image: hub.docker.hamravesh.ir/library/redis:3.2-alpine

volumes:
  ioi_pgdata:
  ioi_static:
  ioi_media:
